INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:52:35] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:52:36] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:52:36] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:52:36] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:52:36] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:51] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:51] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:51] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:51] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:51] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:51] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:52] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:52] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 18:59:52] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:17] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:17] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:17] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:17] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:18] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:18] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:18] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:18] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:10:18] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 530 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:17:19] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 81, in check_password
    row = cursor.fetchone()
AttributeError: 'NoneType' object has no attribute 'fetchone'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 81, in check_password
    row = cursor.fetchone()
AttributeError: 'NoneType' object has no attribute 'fetchone'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 81, in check_password
    row = cursor.fetchone()
AttributeError: 'NoneType' object has no attribute 'fetchone'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:20:01] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 80, in check_password
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:01] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:01] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 80, in check_password
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:02] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 80, in check_password
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:02] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:02] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:02] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:26:02] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:06] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 80, in check_password
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 80, in check_password
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 80, in check_password
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:29:07] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:06] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:06] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 81, in check_password
    row = self.coon.fetchone()
AttributeError: 'User' object has no attribute 'coon'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:06] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:06] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 81, in check_password
    row = self.coon.fetchone()
AttributeError: 'User' object has no attribute 'coon'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:06] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 136, in unregister
    code, message = self.check_password(user_id, password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 81, in check_password
    row = self.coon.fetchone()
AttributeError: 'User' object has no attribute 'coon'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:06] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:07] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:07] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:07] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 140, in unregister
    cursor = self.conn.execute(sql, user_id)
TypeError: not all arguments converted during string formatting
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:30:37] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
ERROR:be.serve:Exception on /auth/unregister [POST]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\anaconda\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\view\auth.py", line 42, in unregister
    code, message = u.unregister(user_id=user_id, password=password)
  File "D:\Ê°åÈù¢Êñá‰ª∂\Â§ß‰∏â‰∏äÁ¨îËÆ∞\Êï∞ÊçÆÁÆ°ÁêÜÁ≥ªÁªü\‰π¶Â∫ó\2022_CDMS_PJ2_REQUIRE-master\2022_cdms_pj2_require\bookstore\be\model\user.py", line 142, in unregister
    self.conn.commit()
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'commit'
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[35m[1mPOST /auth/unregister HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:41] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:42] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:32:42] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:54] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:54] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:54] "[37mPOST /auth/unregister HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:54] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:54] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:54] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:55] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:55] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:38:55] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[37mPOST /auth/unregister HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:45:46] "[37mGET /shutdown HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:38] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:38] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[37mPOST /auth/unregister HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[37mPOST /auth/register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
INFO:werkzeug:127.0.0.1 - - [28/Nov/2022 19:54:39] "[37mGET /shutdown HTTP/1.1[0m" 200 -
